{{- if .Values.mongodb.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}-auth
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  root-password: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
  database-password: {{ .Values.mongodb.auth.databasePassword | b64enc | quote }}
{{- end }}

