apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mongodb
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "mongodb.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}-headless
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mongodb
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "mongodb.selectorLabels" . | nindent 4 }}

